### ISSUE TITLE
Sprite animations created from Atlas

### ISSUE THREAD

**Issue by CyberPlaton** [fountainment/cherrysoda-engine#11]
Hi, I´ve encountered a minor issue which I try to solve and would like to consult you before trying to change the source code locally.

What I´m basically trying to do is, having created a huge atlas of sprites with crunch, to create an animated sprite from that atlas by subsequently specifying the sub-textures for each frame (an example down below).

Currently we animate a sprite created with crunch as follows,
given the definition in JSON
```
{
	"textures":[
		{
			"name":"King",
			"images":[
				{ "n":"tile0", "x":0, "y":42, "w":12, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile4", "x":0, "y":0, "w":13, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile3", "x":0, "y":14, "w":13, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile1", "x":0, "y":28, "w":12, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile2", "x":0, "y":56, "w":12, "h":12, "fx":-9, "fy":-19, "fw":32, "fh":32 }
			]
		}
	]
}
```
we do in .cpp

```	
entity = factory->Begin(this)
		.Add(new  Sprite("assets/King.json"))
		.End();

	entity->Get< Sprite >()->AddLoop("Idle", "tile", 0.16f, { 0, 3, 2, 4, 1 }); // Set corresponding animation frames. Must match JSON file.
```
However, this implies we must have created a JSON file with crunch for every animated sprite (as to my understanding).

**How can we achieve the following**,
given the JSON
```
{
	"textures":[
		{
			"name":"UnitAtlas0",
			"images":[
				{ "n":"HighElf_Knight_A", "x":0, "y":0, "w":112, "h":120, "fx":-72, "fy":-48, "fw":256, "fh":256 },
				{ "n":"HighElf_Knight_B", "x":0, "y":121, "w":112, "h":120, "fx":-72, "fy":-48, "fw":256, "fh":256 },
				{ "n":"Human_Warrior", "x":0, "y":242, "w":112, "h":120, "fx":-72, "fy":-48, "fw":256, "fh":256 }
                // ...

                   ]
                }
}
```
we do in .cpp
```
entity = factory->Begin(this)
		.Add(new  Sprite("assets/UnitAtlas0.json"))
		.End();

	entity->Get< Sprite >()->AddToLoop("Idle", "HighElf_Knight_A"); // We choose a specific sub-texture for the next frame matching the name in JSON.
	entity->Get< Sprite >()->AddToLoop("Idle", "HighElf_Knight_B");
```

**Comment by fountainment** [comment]
You don't have to create a JSON file for every animated sprite, crunch can pack a recursive folder and store the path info.
For an animation image sequence, it's very intuitive to have the same file name prefix with different index. So I'm not sure why you want to add animation with different image name. But there is a hacky way to do this (with the chooser argument, you can create an animation sequence):
```
entity->Get< Sprite >()->Add("Idle", "HighElf_Knight_A", 0.16f, Chooser<StringID>("IdleNext", 1.0f));
entity->Get< Sprite >()->Add("IdleNext", "HighElf_Knight_B", 0.16f, Chooser<StringID>("Idle", 1.0f));
```

Btw, it's recommended to use sprite bank when having a lot of sprite types and animations.
A sprite bank usage reference can be found in: https://github.com/fountainment/bullethelljam2021-bullethelltrial

**Comment by CyberPlaton** [comment]
Thank you for the quick answer. I will check both out!
