### ISSUE TITLE
Rendering primitives

### ISSUE THREAD

**Issue by CyberPlaton** [fountainment/cherrysoda-engine#5]
I would like to ask if there is an intended way to render primitives like lines, circles etc. in 2D space. As my current code oriented on the example FirstTriangle seems not to be correct and not rendered...
Currently in my code I create a line with: 
````
static void CreateLine2D(...):
              GetMesh()->Clear();

              GetMesh()->AddLine( MK_VERT(Vec3(from, 0.0f), color), MK_VERT(Vec3(to, 0.0f), color));

              GetMesh()->SubmitBuffer();

              // ...

             entity->Add(line);
             entity->AddTag(entityTag);
	     scene->Add(entity);
````

Where the line class inherits from MeshGraphicsComponent< PosColorVertex >.
The renderer is an EverythingRenderer with a "sprite"-Effect and OrthoProjection.

**Comment by fountainment** [comment]
In this engine, Mesh class is intended to store vertices information, which has 3D capability.
If you're using "sprite" effect for all rendering, you may not want to use Mesh class.

If you just want to draw a 2D line in current frame, please use **Draw::Line** in Util/Draw.cpp.
You can create your own component class, inherits from GraphicsComponent and override its Render method.

Here is a reference which calls Draw::HollowRect:
```
class HollowRectGraphicsComponent : public GraphicsComponent
{
public:
	CHERRYSODA_DECLARE_COMPONENT(HollowRectGraphicsComponent, GraphicsComponent);

	HollowRectGraphicsComponent(int width, int height)
	: base(false)
	, m_width(width)
	, m_height(height)
	{}

	void Render() override
	{
		Draw::HollowRect(RenderPosition().x, RenderPosition().y, m_width, m_height, GetColor());
	}

private:
	int m_width;
	int m_height;
};
```

**Comment by CyberPlaton** [comment]
Thank you, that helped! But it seems rather unintuitive to have an entity for drawing lines... would it not be better and more straightforward to call the Draw::Line function in a overriden Scene::Render function?

**Comment by CyberPlaton** [comment]
Moreover, as I understood it correctly, the GUI class is for rendering ImGui and if we want to have a non-ImGui GUI we need to implement it ourselves or hack it together from Entities?

**Comment by fountainment** [comment]
For overriding Scene::Render, it's ok to do that, but it's definitely not recommended.
And it might be a little more complicated than what you think.
You will need to handle some more stuff rather than just simply put Draw::Line in it.

Also, by following the rule of ECS, we get some benefits, 
we can easily add and remove graphics, change its rendering order, etc.
And by using GraphicsComponent, we can easily move it, scale it, rotate it, change its color, etc.

If you still insist to get a more intuitive way, it's recommended to create a new Renderer class, for example inherrit from EverythingRenderer and override its Render method.
```
void YourRenderer::Render(Scene* scene)
{
	Graphics::BeginRenderPass(RenderPass());
	Graphics::SetEffect(GetEffect());
	Graphics::UseCurrentRenderPass()->SetCamera(GetCamera());
	Draw::GetSpriteBatch()->Begin();

	// Replace the next three lines with what you want
	scene->Entities()->Render();
	if (Engine::Instance()->ConsoleOpened())
		scene->Entities()->DebugRender(GetCamera());

	Draw::GetSpriteBatch()->End();
	Graphics::SetEffect(nullptr);
	Graphics::EndRenderPass(RenderPass());
}
```

**Comment by fountainment** [comment]
ImGui is integrated for creating GUI for engine and tool.
At this moment, there is no utility for in-game GUI in this engine, you need to implement it youself.

**Comment by fountainment** [comment]
ImGui is integrated for creating GUI for engine and tool.
At this moment, there is no utility for in-game GUI in this engine, you need to implement it youself.
