### ISSUE TITLE
ImGui

### ISSUE THREAD

**Issue by CyberPlaton** [fountainment/cherrysoda-engine#7]
I observed an issue with ImGui.
The following code

`	ImGui::Begin("Test");
	ImGui::Text("Hello World");
	ImGui::End();
`

creates an ImGui window as normal, but writes the text twice. The same duplication is observed with everything within the ImGui windows.

The code is inside a scene update function. And Im not sure whether my code is not in the intended place or there is a bug.

**Comment by fountainment** [comment]
ImGui code is ok to be used anywhere between GUI::Update() and GUI::Render() call, it basically mean anywhere in the scene update. I tested this line locally but didn't observe your issue, I think **the case could be that your ImGui code are called twice in one frame**.

For ImGui, the same window name point to one unique window, so the following code will result in exactly what you described.
```
ImGui::Begin("Test"); ImGui::Text("Hello World"); ImGui::End();
ImGui::Begin("Test"); ImGui::Text("Hello World"); ImGui::End();
```

**Comment by CyberPlaton** [comment]
You were right, I had a duplicate update. Sorry for the trouble
