### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by CyberPlaton** [fountainment/cherrysoda-engine#8]
Could you please elaborate on how to create animations with the current crunch import format?! I dont seem to get it.

Suppose we have a png file with 5 frames. Let the json atlas be as follows

```
{
	"textures":[
		{
			"name":"King",
			"images":[
				{ "n":"tile009", "x":0, "y":42, "w":12, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile013", "x":0, "y":0, "w":13, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile012", "x":0, "y":14, "w":13, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile010", "x":0, "y":28, "w":12, "h":13, "fx":-9, "fy":-18, "fw":32, "fh":32 },
				{ "n":"tile011", "x":0, "y":56, "w":12, "h":12, "fx":-9, "fy":-19, "fw":32, "fh":32 }
			]
		}
	]
}
```

In our code we create an Entity with a sprite component

```
auto entity = factory->Begin( scene )  
		.Add(new  Sprite("assets/King.json"))  
		.End();
```

Lastly we define (following the example "FirstSprite")

```
	entity->Get< Sprite >()->AddLoop("Idle", "tile009");
	entity->Get< Sprite >()->Play("Idle");
	entity->Get< Sprite >()->Position2D(Math::Vec2(100.0f, 100.0f));
	entity->Get< Sprite >()->CenterOrigin();
```

This renders as expected only the Texture named "tile009". However, the goal is to render the images in order like
"tile009"->"tile013"->"tile012"->"tile010"->"tile011".
Naively specifying 
```
entity->Get< Sprite >()->AddLoop("Idle", "King");
```
does not work either.
So I wonder. How am I supposed to create animations?

Thank You in advance!

**Comment by fountainment** [comment]
There is a method of Sprite in Monocle that will be useful in your case, but that was not ported to this engine previously.

By using that method, you can write something like this:
`AddLoop("Idle", "tile", frameDelay, { 9, 13, 12, 10, 11 });`
I did the port just now, you can try that with the latest commit.

Btw, the method used in FirstSprite is trying to find ascending indexes start from 0.
It's strongly recommended to read the Sprite::GetFrames and Atlas::GetAtlasSubtextureFromAtlasAt to understand what is happening.

Thanks for your feedback on using this engine!

**Comment by CyberPlaton** [comment]
Yep, this works perfectly!
Thanks for porting the functions!
