### ISSUE TITLE
Debug Console Behavior

### ISSUE THREAD

**Issue by CyberPlaton** [fountainment/cherrysoda-engine#9]
It would be nice to be able to toggle the GUI ImGui console based on input in a scene.
For example:
```
void Scene::Update()
{
	if (MInput::Keyboard()->Pressed(Keys::OemTilde))
	{
		Engine::ToggleConsole();
	}
}
```
Currently the function "ToggleConsole" is private, my proposition would be to make it protected.

Reason for that could be own implementation of a debug console, as it is in my case. And the only possibility I saw to disable the debug console was ```GUI::Disable();```, which in turn disabled my own implementation too... for that I could not see any solution other than mentioned above.

**Comment by fountainment** [comment]
I did some change, you can try `GUI::DisableInternalConsole()` with the latest commit, I think it fits your case, let me know if there is still any problem.
